### ISSUE TITLE
JSON gets double-escaped by prettification

### ISSUE THREAD

**Issue by leonadler** [vthiery/vscode-prettify-selected-json#1]
Hi! Nice work on your extension!

However, I have noticed a bug:
```
{"specialCharacters":"Umlaut U is \u00fc in JSON"}
```
after _Prettify selected JSON_:
```
{
    "specialCharacters": "Umlaut U is \\u00fc in JSON"
}
```

This is caused by a bug in the [jsonlint](https://github.com/zaach/jsonlint) package you are using, which was last updated 3 years ago.
Would it be safe to use `JSON.parse` instead, or would that break something?

**Comment by vthiery** [comment]
Hi!
Thank you vm for spotting this issue. I just fixed it as you proposed.
Sorry for the delay, it just slipped out of my mind!
